name: 比赛信息更新
description: 适用于已经添加的比赛需要更新如比赛链接，时间，备注等信息（注：比赛状态会自动更新，无需提交申请）
title: "<更新比赛>"
labels: []
assignees:
  - ProbiusOfficial 
body:
  - type: input
    id: name
    attributes:
      label: <更新>赛事名称
      placeholder: HelloCTF2024 / 第?届xx赛/xx杯...
    validations:
      required: true

  - type: input
    id: link
    attributes:
      label: 比赛链接
      placeholder: https://hello-ctf.com/
    validations:

  - type: input
    id: type
    attributes:
      label: 比赛类型
      description: 个人赛请直接填写个人赛，团队赛请注明人数。
      placeholder: 个人赛 / 团队赛|1-3人
    validations:

  - type: input
    id: bmks
    attributes:
      label: 报名开始时间
      description: 注意时间格式统一使用 yyyy年-MM月-dd日 HH:mm
      placeholder: 2024年01月01日 00:00 
    validations:

  - type: input
    id: bmjz
    attributes:
      label: 报名结束时间
      placeholder: 2024年01月02日 00:00 
    validations:
  
  - type: input
    id: bsks
    attributes:
      label: 比赛开始时间
      placeholder: 2024年01月03日 00:00 
    validations:

  - type: input
    id: bsjs
    attributes:
      label: 比赛结束时间
      placeholder: 2024年01月04日 00:00 
    validations:
  
  - type: input
    id: readmore
    attributes:
      label: 备注信息
      description: 有关比赛的其他信息，如赛事交流群、赛事详情等内容。
      placeholder: QQ群：590430891
    validations:
  
