name: Save Issue as JSON

on:
  issues:
    types: [opened]

permissions:
    contents: write

jobs:
  save-and-create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
     
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      
      - name: Save Issue to JSON
        run: |
         line=$(cat ${GITHUB_EVENT_PATH} | jq -r '.issue.body' | head -n 1)
         if [ "$line" != "### 赛事名称" ] ; then
            exit 0
         fi
         file_content=$(cat ${GITHUB_EVENT_PATH} | jq -r '.issue.body')
         echo $file_content > temp

          mkdir -p .github/issues
          mkdir -p ./ReviewPending/

          mv temp .github/issues/

          python getIssueBody.py
      
      - name: Check for changes
        id: check_changes
        run: |
          git add .
          if [ -n "$(git status --porcelain)" ]; then
            echo "CHANGES=true" >> $GITHUB_ENV
          fi

      - name: Commit and push changes
        if: env.CHANGES == 'true'
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Automatically update
